AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloud formation template for residential building project'

Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket
    Default: 'residential-building-bucket'
  
  TopicName:
    Type: String
    Description: Name for the SNS topic
    Default: 'residential-building-topic'

Resources:
  ResidentialBuildingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Suspended
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: Environment
          Value: Sample
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ResidentialBuildingTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      DisplayName: !Ref TopicName
      Tags:
        - Key: Name
          Value: !Ref TopicName
        - Key: Environment
          Value: Sample

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref ResidentialBuildingBucket
  
  S3BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt ResidentialBuildingBucket.Arn

  SNSTopicName:
    Description: Name of the SNS topic
    Value: !GetAtt ResidentialBuildingTopic.TopicName
  
  SNSTopicArn:
    Description: ARN of the SNS topic
    Value: !Ref ResidentialBuildingTopic