# @SoftwareProject.GenerationService_HostAddress = http://localhost:5191

# GET {{SoftwareProject.GenerationService_HostAddress}}/weatherforecast/
# Accept: application/json

@ProgramProject.GenerationService_HostAddress = http://localhost:5191

GET {{ProgramProject.GenerationService_HostAddress}}/weatherforecast/
Accept: application/json

###
