AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloud formation template for vehicle project (SNS topic)'

Parameters:
  TopicName:
    Type: String
    Description: Name for the SNS topic
    Default: 'vehicle-topic'

Resources:
  VehicleTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      DisplayName: !Ref TopicName
      Tags:
        - Key: Name
          Value: !Ref TopicName
        - Key: Environment
          Value: Lab3

Outputs:
  SNSTopicName:
    Description: Name of the SNS topic
    Value: !GetAtt VehicleTopic.TopicName

  SNSTopicArn:
    Description: ARN of the SNS topic
    Value: !Ref VehicleTopic
