<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d9196e3d-e011-40da-8419-ada6548d1b1e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.2.29" />
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vehicle.ServiceDefaults\Vehicle.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
